/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubCampaignIdRouteImport } from './routes/hub.$campaignId'
import { Route as ApiProxySplatRouteImport } from './routes/api/proxy.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/hub/',
  path: '/hub/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCampaignIdRoute = HubCampaignIdRouteImport.update({
  id: '/hub/$campaignId',
  path: '/hub/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProxySplatRoute = ApiProxySplatRouteImport.update({
  id: '/api/proxy/$',
  path: '/api/proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/uploads': typeof UploadsRoute
  '/hub/$campaignId': typeof HubCampaignIdRoute
  '/hub/': typeof HubIndexRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/uploads': typeof UploadsRoute
  '/hub/$campaignId': typeof HubCampaignIdRoute
  '/hub': typeof HubIndexRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/uploads': typeof UploadsRoute
  '/hub/$campaignId': typeof HubCampaignIdRoute
  '/hub/': typeof HubIndexRoute
  '/api/proxy/$': typeof ApiProxySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/uploads' | '/hub/$campaignId' | '/hub/' | '/api/proxy/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/uploads' | '/hub/$campaignId' | '/hub' | '/api/proxy/$'
  id:
    | '__root__'
    | '/'
    | '/uploads'
    | '/hub/$campaignId'
    | '/hub/'
    | '/api/proxy/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadsRoute: typeof UploadsRoute
  HubCampaignIdRoute: typeof HubCampaignIdRoute
  HubIndexRoute: typeof HubIndexRoute
  ApiProxySplatRoute: typeof ApiProxySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/': {
      id: '/hub/'
      path: '/hub'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$campaignId': {
      id: '/hub/$campaignId'
      path: '/hub/$campaignId'
      fullPath: '/hub/$campaignId'
      preLoaderRoute: typeof HubCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proxy/$': {
      id: '/api/proxy/$'
      path: '/api/proxy/$'
      fullPath: '/api/proxy/$'
      preLoaderRoute: typeof ApiProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadsRoute: UploadsRoute,
  HubCampaignIdRoute: HubCampaignIdRoute,
  HubIndexRoute: HubIndexRoute,
  ApiProxySplatRoute: ApiProxySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
